apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rn9m9si8x-java-quarkus
  janus-idp.io/tekton: rn9m9si8x-java-quarkus
  backstage.io/kubernetes-id: rn9m9si8x-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rn9m9si8x-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
